### PR TITLE
Extra mouse input for easier knob editing

### PR DESCRIPTION
**Pull request by noisecode3**
Hi, I added some extra mouse button input.
Right click work like holding down Ctrl and middle mouse activate default knob value like shift key.
If you don't like it, never mind.

### CODE REVIEW

**Comment by zamaudio** [comment]
@martinbangens thank you for this.  Can you also please consider adding it to DPF? I would like to keep things in sync with what @falkTX wants to maintain in DPF,  otherwise we get out of sync.

**Comment by martinbangens** [comment]
Sure @zamaudio ! btw I think It better if I did else after the check for ev.button == 3.
because if that one is not true ALL other mouse buttons must sett fRightClicked = false.
IF you know what I mean :) for safety and to make it cleaner.
But it will only take those other 2 mouse button anyway from the first check

**Comment by martinbangens** [comment]
I see how I could add that in ImageWidgets.cpp in DPF but the real question is. To knob or not to knob?
What dose you're mouse say about this? What dose my mouse say about this? It should be harmless, it's just to extra
mouse button inputs. And also what's the exact correct way to add that functionality?? I need a day to think about this. also there a lot going on over here.

**Comment by martinbangens** [comment]
I tested all plugins, jack stand alone, LV2 in Ardour and VST2 in Renoise. I haven't tested DSSI yet, I must try to add this to DPF.
It seem to work best with some if statements like this, I did try another approach but I messed up middle mouse click,
this fist one is simple and I reverted back to it. I added right mouse + ctrl click that I think people will like for mastering and give them better control.

I think I'm done here, have fun!

**Comment by zamaudio** [comment]
@noisecode3 I cannot merge this, if you are still keen to do these changes, i suggest adding a PR to distrho/dpf

**Comment by noisecode3** [comment]
Sure I could look into it, in the holidays, think we can close this PR for now :)

**Pull request closed without merging**
